# Generated by Django 3.2 on 2021-09-30 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0002_auto_20210928_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('term', models.CharField(choices=[('half yearly', 'Half Yearly'), ('yearly', 'Yearly'), ('pre test', 'Pre Test'), ('test', 'Test'), ('others', 'Others')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.PositiveIntegerField(null=True)),
                ('cq_marks', models.PositiveIntegerField(blank=True, default=0)),
                ('mcq_marks', models.PositiveIntegerField(blank=True, default=0)),
                ('practical_marks', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.examination')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='department.department')),
            ],
        ),
    ]
