# Generated by Django 3.2 on 2021-10-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_examination_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='point',
            field=models.FloatField(default=0),
        ),
    ]
