# Generated by Django 3.2 on 2021-10-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_grade_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='term',
            field=models.CharField(choices=[('HY', 'Half Yearly'), ('Y', 'Yearly'), ('PT', 'Pre Test'), ('T', 'Test'), ('O', 'Others')], max_length=20),
        ),
    ]
