# Generated by Django 3.2 on 2021-10-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_alter_examination_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='term',
            field=models.CharField(choices=[('HY', 'Half Yearly'), ('Y', 'Yearly'), ('PT', 'Pre Test'), ('T', 'Test'), ('O', 'Others')], max_length=2),
        ),
    ]
