# Generated by Django 3.2 on 2021-09-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='picture',
            field=models.ImageField(blank=True, default='male.jpeg', null=True, upload_to='pictures/teacher'),
        ),
    ]
