# Generated by Django 3.2 on 2021-09-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='father_name',
            new_name='father',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='mother_name',
            new_name='mother',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='picture',
            field=models.ImageField(blank=True, default='pictures/male.jpeg', null=True, upload_to='pictures/teacher'),
        ),
    ]
