# Generated by Django 3.2 on 2021-09-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20211001_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='degree_1',
            new_name='honours',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='degree_2',
            new_name='masters',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='degree_3',
            new_name='others',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='degree_others',
        ),
    ]
