# Generated by Django 3.2 on 2021-07-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Title here ...', max_length=200)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, default='Here should be desc...', max_length=1000)),
            ],
        ),
    ]
