# Generated by Django 3.2 on 2021-07-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='published_date',
            field=models.DateField(default='2021-7-02'),
        ),
    ]
