# Generated by Django 3.2 on 2021-07-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
