# Generated by Django 3.2 on 2021-09-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallery_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
    ]
