# Generated by Django 3.2 on 2021-09-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_subjectcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcode',
            name='code',
            field=models.CharField(max_length=7),
        ),
    ]
