# Generated by Django 3.2 on 2021-09-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_subjectcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectcode',
            name='type',
            field=models.CharField(choices=[('compulsory', 'Compulsory'), ('ccience ', 'Science '), ('business studies', 'Business Studies'), ('humanities ', 'Humanities')], default='compulsory', max_length=100),
        ),
    ]
