# Generated by Django 3.2 on 2021-09-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_subjectcode_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectCode',
        ),
    ]
