# Generated by Django 3.2 on 2021-09-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_delete_subjectcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image_5',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
