# Generated by Django 3.2 on 2021-09-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20210928_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Title here ...', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='carousel')),
            ],
            options={
                'verbose_name_plural': 'Carousel',
            },
        ),
    ]
