# Generated by Django 3.2 on 2021-10-21 16:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_noticeboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 16, 2, 1, 764000, tzinfo=utc)),
        ),
    ]
