# Generated by Django 3.2 on 2021-10-21 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_alter_noticeboard_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
