# Generated by Django 3.2 on 2021-10-21 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_group'),
        ('gallery', '0015_alter_noticeboard_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='department',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
            preserve_default=False,
        ),
    ]
