# Generated by Django 3.2 on 2021-10-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_noticeboard_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Event',
        ),
    ]
