# Generated by Django 3.2 on 2021-07-27 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('roll', models.PositiveIntegerField()),
                ('group', models.CharField(choices=[('s', 'Science'), ('h', 'Humanities'), ('b', 'Business Studies')], max_length=1)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('thana', models.CharField(blank=True, max_length=100, null=True)),
                ('post', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, default='girl.jpeg', null=True, upload_to='')),
                ('date_of_birth', models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('optional_sub', models.CharField(max_length=10)),
                ('subjects', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectsForScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optional', models.CharField(choices=[('Biology', 'Biology'), ('Higher Mathematics', 'Higher Mathematics')], default='Higher Mathematics', max_length=100)),
                ('subject_4', models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry')], default='Physics', max_length=100)),
                ('subject_5', models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry')], default='Chemistry', max_length=100)),
                ('subject_6', models.CharField(choices=[('Biology', 'Biology'), ('Higher Mathematics', 'Higher Mathematics')], default='Biology', max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'SubjectsForScience',
                'verbose_name_plural': 'SubjectsForScience',
            },
        ),
        migrations.CreateModel(
            name='SubjectsForHumanities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optional', models.CharField(choices=[('Islamic Studies', 'Islamic Studies'), ('Logic', 'Logic'), ('Civics', 'Civics'), ('Economics', 'Economics'), ('Islamic History', 'Islamic History')], max_length=100)),
                ('subject_4', models.CharField(choices=[('Logic', 'Logic'), ('Civics', 'Civics'), ('Economics', 'Economics'), ('Islamic History', 'Islamic History')], max_length=100)),
                ('subject_5', models.CharField(choices=[('Logic', 'Logic'), ('Civics', 'Civics'), ('Economics', 'Economics'), ('Islamic History', 'Islamic History')], max_length=100)),
                ('subject_6', models.CharField(choices=[('Logic', 'Logic'), ('Civics', 'Civics'), ('Economics', 'Economics'), ('Islamic History', 'Islamic History')], max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'SubjectsForHumanities',
                'verbose_name_plural': 'SubjectsForHumanities',
            },
        ),
        migrations.CreateModel(
            name='SubjectsForBusinessStudies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optional', models.CharField(max_length=100)),
                ('subject_4', models.CharField(max_length=100)),
                ('subject_5', models.CharField(max_length=100)),
                ('subject_6', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'SubjectsForBusinessStudies',
                'verbose_name_plural': 'SubjectsForBusinessStudies',
            },
        ),
    ]
