# Generated by Django 3.2 on 2021-07-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_stuinfo_optional_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuinfo',
            name='optional_sub',
        ),
        migrations.AddField(
            model_name='stuinfo',
            name='optional_sub1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stuinfo',
            name='optional_sub2',
            field=models.IntegerField(default=0),
        ),
    ]
