# Generated by Django 3.2 on 2021-07-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210727_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='optional_sub1',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='optional_sub2',
            field=models.CharField(max_length=40),
        ),
    ]
