# Generated by Django 3.2 on 2021-09-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20210929_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='group',
            field=models.CharField(choices=[('science', 'Science'), ('humanities', 'Humanities'), ('business studies', 'Business Studies')], default='science', max_length=20),
        ),
    ]
