# Generated by Django 3.2 on 2021-09-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_fileupload_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, default='pictures/girl.jpeg', upload_to='student'),
        ),
    ]
