# Generated by Django 3.2 on 2021-09-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_student_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='compulsory_subjects',
            new_name='subjects',
        ),
    ]
