# Generated by Django 3.2 on 2021-10-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_roll',
            field=models.PositiveIntegerField(),
        ),
    ]
