# Generated by Django 3.2 on 2021-10-10 11:38

import django.core.validators
from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20211010_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(2000), student.models.max_value_current_year]),
        ),
    ]
