# Generated by Django 3.2 on 2021-10-10 11:43

import django.core.validators
from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_fileupload_admission_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='admission_year',
            field=models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(2020), student.models.max_value_current_year]),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(2020), student.models.max_value_current_year]),
        ),
    ]
