# Generated by Django 3.2 on 2021-10-19 13:29

import django.core.validators
from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_alter_student_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='admission_year',
            field=models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(2015), student.models.max_value_current_year]),
        ),
    ]
