# Generated by Django 3.2 on 2021-09-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=7)),
                ('type', models.CharField(choices=[('compulsory', 'Compulsory'), ('ccience ', 'Science '), ('business studies', 'Business Studies'), ('humanities ', 'Humanities')], default='compulsory', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
