# Generated by Django 3.2 on 2021-09-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20210928_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='group',
            field=models.CharField(choices=[('science', 'Science'), ('humanities', 'Humanities'), ('business studies', 'Business studies')], max_length=20),
        ),
    ]
