# Generated by Django 3.2 on 2021-10-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='group',
            field=models.CharField(choices=[('SC', 'Science'), ('HM', 'Humanities'), ('BS', 'Business studies')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectcode',
            name='type',
            field=models.CharField(choices=[('CS', 'Compulsory'), ('SC ', 'Science '), ('BS', 'Business Studies'), ('HM ', 'Humanities')], default='CS', max_length=100),
        ),
    ]
